meta:
  availability_zones: (( merge ))
  ipmask: (( merge ))

  consul_templates:
    - name: vm-consul
      release: consul
    - name: consul
      release: consul

jobs:
  - name: consul_leader_z1
    instances: 1
    persistent_disk: 4096
    networks:
      - name: con1
    properties:
      consul:
        cluster:
          join_host: (( meta.ipmask ".4.6" ))
          size: 3
      network: con1
    resource_pool: small_z1
    templates: (( meta.consul_templates ))

  - name: consul_followers_z1
    instances: 2
    networks:
      - name: con1
    persistent_disk: 4096
    properties:
      consul:
        cluster:
          join_hosts: 
          - (( meta.ipmask ".4.6" ))
          - (( meta.ipmask ".4.7" ))
          - (( meta.ipmask ".4.8" ))
          size: 3
      network: con1
    resource_pool: small_z1
    templates: (( meta.consul_templates ))
