networks: (( merge ))

meta:
  ipmask: (( merge ))
  cf1_quad: (( merge ))

  consul_templates:
    - name: vm-consul
      release: consul
    - name: consul
      release: consul

jobs:
  - name: consul_leader_z1
    instances: 1
    persistent_disk: 4096
    networks:
      - name: con1
        static_ips: (( static_ips(0) ))
    properties:
      consul:
        cluster:
          join_host: (( meta.ipmask meta.cf1_quad ".80" ))
          size: 3
      network: con1
    resource_pool: small_z1
    templates: (( meta.consul_templates ))

  - name: consul_followers_z1
    instances: 2
    networks:
      - name: con1
        static_ips: (( static_ips(1,2) ))
    persistent_disk: 4096
    properties:
      consul:
        cluster:
          join_hosts: 
          - (( meta.ipmask meta.cf1_quad ".80" ))
          - (( meta.ipmask meta.cf1_quad ".81" ))
          - (( meta.ipmask meta.cf1_quad ".82" ))
          size: 3
      network: con1
    resource_pool: small_z1
    templates: (( meta.consul_templates ))
